
POST http://localhost:3000/employee
Content-Type: application/json

{
    "name":"Pavan Kalyan",
    "designation":"Full Stack Developer",
    "phone":"9391545920",
    "email":"pavankalayn@gmail.com",
    "age":24
}
###

GET http://localhost:3000/employee?designation=Backend
###

PUT http://localhost:3000/employee/6420ef19bab965dc0a2a0190
Content-Type: application/json

{
   "designation":"Full Stack Developer"
}
###

DELETE  http://localhost:3000/employee/6420f21b463fef699f460bcc
